### ISSUE TITLE
vrelay

### ISSUE THREAD

**Issue by WolfxSoul** [swrlly/valorlib#2]
Hello I was using VRelay last update and it worked perfectly, but this most recently in game update caused some issues. After I updated VRelay again it causes my projectiles to dc me. Abilities work fine it's just weapons. ANY HELP? (sent twice?)

**Comment by swrlly** [comment]
whenever this happens, you need to read the client's code to understand what fields were modified / whether a new field appeared. from there, you can update packet structures yourself.

 i pushed a fix but will not likely update this going forward.
